
name: Publish release candidate

on:

  workflow_dispatch:

jobs:

  checks:

    name: Perform checks
    uses: digita-ai/handlersjs/.github/workflows/checks.yml@develop

  prerelease:

    name: Publish release candidate
    needs: checks
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout ref
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure git
        run: | 
          git config user.name ${{github.actor}}
          git config user.email ${{github.actor}}@users.noreply.github.com
          git remote set-url origin https://${{github.actor}}:${{secrets.GA_TOKEN}}@github.com/${{github.repository}}.git

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://npm.pkg.github.com
  
      - name: Install dependencies
        run: npm run bootstrap
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build package
        run: npm run build:all

      - name: Publish package
        run: npx lerna publish --conventional-commits --conventional-prerelease --preid rc --dist-tag rc --yes --no-push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes
        run: git -c "http.https://github.com/.extraheader=" push
